@tool
class_name DBEnumExporter
extends RefCounted
## Генерирует .gd-файл с настоящими enum'ами из DBDatabase,
## чтобы ENUM-поля были доступны в коде как константы (GameEnums.Element.FIRE).

const _HEADER := \
	"# ============================================================\n" + \
	"# AUTO-GENERATED by GD Database — НЕ РЕДАКТИРОВАТЬ ВРУЧНУЮ.\n" + \
	"# Перегенерируй кнопкой «Gen Enums» в нижней панели GD Database.\n" + \
	"# Источник     : %s\n" + \
	"# Сгенерировано: %s\n" + \
	"# ============================================================\n"

static func generate_source(db: DBDatabase, class_name_str := "GameEnums",
		enum_refs: PackedStringArray = PackedStringArray(),
		include_value_enums := true,
		include_columns := false,
		column_tables: PackedStringArray = PackedStringArray()) -> String:
	var out := PackedStringArray()
	out.append(_HEADER % [
		db.resource_path if db and not db.resource_path.is_empty() else "<in-memory>",
		Time.get_datetime_string_from_system()
	])
	out.append("@tool")
	out.append("class_name %s" % class_name_str)
	out.append("## Enum'ы, извлечённые из схем базы данных.")
	out.append("")

	# ── 1. Enum-поля (значения). enum_refs пустой => все. ──
	if include_value_enums:
		var enums := _collect(db, enum_refs)
		var names := enums.keys()
		names.sort()
		for ename in names:
			_emit_enum(out, ename, enums[ename])

	# ── 2. Авто: enum имён колонок по таблицам. column_tables пустой => все. ──
	if include_columns:
		var cols := _collect_columns(db, column_tables)
		var cnames := cols.keys()
		cnames.sort()
		if cnames.size() > 0:
			out.append("# ── Имена колонок таблиц (авто-обход) ──")
			out.append("")
			for cname in cnames:
				_emit_enum(out, cname, cols[cname])

	return "\n".join(out)

static func export_to_file(db: DBDatabase, path: String, class_name_str := "GameEnums",
		enum_refs: PackedStringArray = PackedStringArray(),
		include_value_enums := true,
		include_columns := false,
		column_tables: PackedStringArray = PackedStringArray()) -> Error:
	var src := generate_source(db, class_name_str, enum_refs,
		include_value_enums, include_columns, column_tables)
	var f := FileAccess.open(path, FileAccess.WRITE)
	if f == null:
		return FileAccess.get_open_error()
	f.store_string(src)
	f.close()
	return OK

# ── Внутреннее ────────────────────────────────────────────────────────────────

static func _collect(db: DBDatabase, enum_refs: PackedStringArray = PackedStringArray()) -> Dictionary:
	var out := {}   # enum_name -> PackedStringArray
	if db == null:
		return out
	var use_filter := enum_refs.size() > 0
	for tname in db.get_table_names():
		var t := db.get_table(tname)
		if t == null or t.schema == null:
			continue
		for f: DBFieldDef in t.schema.fields:
			if f.field_type != DBFieldDef.FieldType.ENUM or f.enum_values.is_empty():
				continue
			if not f.enum_ref.is_empty():
				continue   # ссылка на чужой enum — источник его уже сгенерирует
			var src_key := "%s/%s" % [t.schema.schema_name, f.field_name]
			if use_filter and not enum_refs.has(src_key):
				continue
			var base := _to_type_name(f.field_name)
			var ename := base
			# Имя занято другим набором значений → разводим именем схемы.
			if out.has(ename) and not _equal(out[ename], f.enum_values):
				ename = _to_type_name(t.schema.schema_name) + base
			out[ename] = f.enum_values
	return out


static func _equal(a: PackedStringArray, b: PackedStringArray) -> bool:
	if a.size() != b.size():
		return false
	for i in range(a.size()):
		if a[i] != b[i]:
			return false
	return true

static func _is_word_char(ch: String) -> bool:
	return (ch >= "A" and ch <= "Z") or (ch >= "a" and ch <= "z") or (ch >= "0" and ch <= "9")

static func _to_member(s: String) -> String:
	var r := ""
	for ch in s.strip_edges():
		r += ch if _is_word_char(ch) else "_"
	r = r.to_upper()
	while r.find("__") != -1:
		r = r.replace("__", "_")
	r = r.lstrip("_").rstrip("_")
	if r.is_empty():
		r = "VALUE"
	if r[0] >= "0" and r[0] <= "9":
		r = "_" + r
	return r

static func _to_type_name(s: String) -> String:
	var n := s.strip_edges().to_pascal_case()
	if n.is_empty():
		n = "Enum"
	if n[0] >= "0" and n[0] <= "9":
		n = "_" + n
	return n

## Авто-обход: для каждой таблицы собираем enum из имён её колонок.
## { "TableNameColumns": PackedStringArray(имена полей) }.
## tables_filter пустой => все таблицы.
static func _collect_columns(db: DBDatabase, tables_filter: PackedStringArray = PackedStringArray()) -> Dictionary:
	var out := {}
	if db == null:
		return out
	var use_filter := tables_filter.size() > 0
	for tname in db.get_table_names():
		if use_filter and not tables_filter.has(tname):
			continue
		var t := db.get_table(tname)
		if t == null or t.schema == null:
			continue
		var cols := PackedStringArray()
		for f: DBFieldDef in t.schema.fields:
			cols.append(f.field_name)
		if cols.is_empty():
			continue
		var ename := _to_type_name(tname) + "Columns"
		out[ename] = cols
	return out

## Печатает один enum + LABELS + *_label() в выходной буфер.
static func _emit_enum(out: PackedStringArray, ename: String, values: PackedStringArray) -> void:
	out.append("enum %s {" % ename)
	var seen := {}
	for i in range(values.size()):
		var member := _to_member(values[i])
		if seen.has(member):
			member = "%s_%d" % [member, i]
		seen[member] = true
		out.append("\t%s = %d," % [member, i])
	out.append("}")

	var quoted := PackedStringArray()
	for v in values:
		quoted.append("\"%s\"" % v.replace("\\", "\\\\").replace("\"", "\\\""))
	var up = ename.to_snake_case().to_upper()
	out.append("const %s_LABELS: PackedStringArray = [%s]" % [up, ", ".join(quoted)])
	out.append("static func %s_label(value: int) -> String:" % ename.to_snake_case())
	out.append("\treturn %s_LABELS[value] if value >= 0 and value < %s_LABELS.size() else \"\"" % [up, up])
	out.append("")
